### ISSUE TITLE
Infinity

### ISSUE THREAD

**Issue by debsahu** [Benik3/Adalight_WS2812_ESP8266_Non-blocking#1]
When smooth is 0, 1/0 evaluates to infinity

https://github.com/Benik3/Adalight_WS2812_ESP8266_Non-blocking/blob/2cd032bd3f1239f597bea3b7f4cf974abe5886bb/Adalight_ESP/Adalight_ESP.ino#L77

**Comment by Benik3** [comment]
When Smooth is 0 the `#if SMOOTH` should be false so it will jump to `#else` https://github.com/Benik3/Adalight_WS2812_ESP8266_Non-blocking/blob/2cd032bd3f1239f597bea3b7f4cf974abe5886bb/Adalight_ESP/Adalight_ESP.ino#L111-L123

**Comment by debsahu** [comment]
got it, any reason why you using gamma tables instead of NeoPixelBus's Gamma Correction?

**Comment by Benik3** [comment]
I have this Gamma table measured by colorimeter (Eye one display) on my LEDs (APA102).  
This table has slower gradient on the beginning and in my opinion it fits better.  
Even the original Makuna table is not the best implementation. I made a correction, but it wasn't merged: 
https://github.com/Makuna/NeoPixelBus/pull/242

**Comment by debsahu** [comment]
Thanks, got it. how are you processing 500000 baud rate? I'm using Prismatic that has upper limit on 115200. Sorry so many questions.

**Comment by debsahu** [comment]
nevermind https://www.partsnotincluded.com/ambilight/custom-serial-baud-rates-in-prismatik/

**Comment by Benik3** [comment]
Do you have latest version of Prismatic? It was in one of the latest update:
https://github.com/psieg/Lightpack/releases
But yes, you can also edit it manually :)

P.S. I don't use original Prismatic, it was deprecated...
